'use strict';
  const API='https://vpawamwfozaqruxlfcor.supabase.co/functions/v1';
  const $=id=>document.getElementById(id);
  const svg=$('graph'), NS='http://www.w3.org/2000/svg';
  const S={nodes:new Map(),edges:new Map(),selected:null,root:null,scale:1,tx:0,ty:0,auto:true,pan:null,drag:null,clickTimer:null,typed:false,searchSeq:0,deepSeq:0,stateRows:new Map(),liveStates:new Set(),activeResult:-1,manual:false,renderPending:false};
  const COLORS={company:'#ff9f1c',organization:'#ff9f1c',person:'#76e05f',agent:'#9b6cff',address:'#18cfff',money:'#35f28b',control:'#ff4fa3',finance:'#ffd166',agentlink:'#b388ff',source:'#9aa9b8'};
  const BASE_SWEEP_NATIVE=new Set(['CO','CT','FL','NY','OR','PA','IA','TX']);
  const moneyRE=/(OWNER|OWNERSHIP|SUBSIDIARY|PARENT|BENEFICIAL|SHAREHOLDER|GENERAL_PARTNER|PARTNER|MANAGING_MEMBER|MEMBER|MANAGER|INVEST|FUND|LENDER|BORROWER|LOAN|FINANC|PAYMENT|CONTRACT|PURCHASE|ACQUISITION|MERGER)/i;
  const financeRE=/(CFO|CHIEF_FINANCIAL|TREASURER|CONTROLLER|ACCOUNTING|FINANCE)/i;
  const controlRE=/(PRESIDENT|CEO|CHIEF_EXECUTIVE|DIRECTOR|CHAIR|GOVERNOR|SECRETARY|OFFICER|INCORPORATOR|ORGANIZER)/i;
  const historicalRE=/(inactive|dissolv|terminat|forfeit|revok|withdraw|merged|cancel|expired|relinquish|delinquent|noncompliant|converted|suspend)/i;

  function esc(s){return String(s??'').replace(/\s+/g,' ').trim()}
  function safeArray(x){return Array.isArray(x)?x:[]}
  function uniq(a){return [...new Set(a.filter(Boolean))]}
  function now(){return new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}
  function event(msg){const h=$('hist');if(h.classList.contains('muted')){h.classList.remove('muted');h.textContent=''}const d=document.createElement('div');d.className='event';d.append(document.createTextNode(msg));const t=document.createElement('time');t.textContent=now();d.append(t);h.prepend(d);while(h.children.length>70)h.lastChild.remove()}
  function status(msg,kind='ok'){$('status').textContent=msg;$('status').style.color=kind==='err'?'#ff7883':kind==='wait'?'#e7c66a':'#76f6a4'}
  function toast(msg){const d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),2400)}
  async function get(path,ms=30000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(API+path,{headers:{Accept:'application/json'},signal:c.signal});const text=await r.text();let b={};try{b=JSON.parse(text)}catch{throw new Error(`Non-JSON response (${r.status})`)}if(!r.ok)throw new Error(b.error||`HTTP ${r.status}`);return b}finally{clearTimeout(t)}}

  function nodeKind(r){const types=uniq([...(safeArray(r.member_types)),r.entity_type,r.identity_class].map(x=>String(x||'').toLowerCase()));if(types.some(x=>x.includes('address')))return'address';if(types.some(x=>x.includes('person')||x.includes('officer')))return'person';if(types.some(x=>x.includes('agent')))return'agent';return'company'}
  function isHist(r){return !!r.historical||safeArray(r.lifecycle_statuses).length>0||safeArray(r.statuses).some(x=>historicalRE.test(String(x)))||historicalRE.test(String(r.status||''))}
  function normIdentity(r){const id=r.identity_id||r.parent_identity_id||r.id;return{id,label:esc(r.canonical_name||r.name||'Unnamed entity'),kind:nodeKind(r),historical:isHist(r),statuses:uniq([...(safeArray(r.statuses)),r.status].map(esc)),lifecycle:uniq(safeArray(r.lifecycle_statuses).map(esc)),jurisdictions:uniq([...(safeArray(r.jurisdictions)),r.jurisdiction].map(esc)),sources:safeArray(r.sources),raw:r}}
  function formatAddress(a){if(!a)return'Unknown address';return uniq([a.line1,a.line2,a.city,a.region,a.postal_code,a.country].map(esc)).join(', ')}
  function stripUnit(s=''){return esc(s).replace(/\s+(?:suite|ste|unit|apt|apartment|floor|fl|room|rm|office|ofc|#)\s*#?\s*[a-z0-9-]+/ig,' ').replace(/\s+/g,' ').trim()}
  function fallbackPremiseKey(a={}){const street=stripUnit([a.line1,a.line2].filter(Boolean).join(' ')).toLowerCase().replace(/[.,;:#]+/g,' ').replace(/\b(street)\b/g,'st').replace(/\b(road)\b/g,'rd').replace(/\b(avenue)\b/g,'ave').replace(/\b(boulevard)\b/g,'blvd').replace(/\b(drive)\b/g,'dr').replace(/\b(lane)\b/g,'ln').replace(/\b(court)\b/g,'ct').replace(/\b(highway)\b/g,'hwy').replace(/\b(parkway)\b/g,'pkwy').replace(/\b(place)\b/g,'pl').replace(/\b(circle)\b/g,'cir').replace(/\b(terrace)\b/g,'ter').replace(/\s+/g,' ').trim().replace(/\s+(?:st|rd|ave|blvd|dr|ln|ct|hwy|pkwy|pl|cir|ter|rte|tpke|way)(?:\s+(n|s|e|w|ne|nw|se|sw))?$/i,(_,d)=>d?' '+d:'');const zip=esc(a.postal_code).replace(/\D/g,'').slice(0,5),country=/^(|us|usa|u s|united states|united states of america)$/i.test(esc(a.country))?'us':esc(a.country).toLowerCase();return [street,esc(a.city).toLowerCase(),esc(a.region).toLowerCase(),zip,country].filter(Boolean).join(' ').replace(/\s+/g,' ').trim()}
  function premiseKey(r={},a={}){return esc(r.address_premise_key||r.address_merge_key||a.premise_key)||fallbackPremiseKey(a)}
  function premiseLabel(a={}){const line=stripUnit([a.line1,a.line2].filter(Boolean).join(' '));return uniq([line,a.city,a.region,a.postal_code,a.country].map(esc)).join(', ')||'Unknown address'}
  function mergeAddressRaw(a={},b={}){const variants=[...safeArray(a.variants),...safeArray(b.variants),a.address_variant,b.address_variant,a.address,b.address].filter(Boolean),ids=uniq([...safeArray(a.equivalent_address_ids),...safeArray(b.equivalent_address_ids),a.address_variant_id,b.address_variant_id,a.canonical_address_id,b.canonical_address_id,a.address_id,b.address_id]);return{...a,...b,address_premise_key:b.address_premise_key||a.address_premise_key||b.address_merge_key||a.address_merge_key,equivalent_address_ids:ids,variants}}
  function addNode(n,anchor=null){if(!n?.id)return null;const old=S.nodes.get(n.id);if(old){const keep={x:old.x,y:old.y,w:old.w,h:old.h,expanded:old.expanded,loading:old.loading,_placed:old._placed};if(old.kind==='address'&&n.kind==='address'){old.label=old.label&&old.label.length<=n.label.length?old.label:n.label;old.jurisdictions=uniq([...(old.jurisdictions||[]),...(n.jurisdictions||[])]);old.sources=[...(old.sources||[]),...(n.sources||[])];old.raw=mergeAddressRaw(old.raw||{},n.raw||{});Object.assign(old,keep);return old}Object.assign(old,n,keep);return old}const base={x:0,y:0,w:n.kind==='address'?235:215,h:70,expanded:false,loading:false};const nn=Object.assign(base,n);if(anchor&&S.nodes.has(anchor)){const p=S.nodes.get(anchor);nn.x=p.x+320;nn.y=p.y}else if(S.nodes.size){nn.x=(S.nodes.size%4)*260;nn.y=Math.floor(S.nodes.size/4)*100}S.nodes.set(nn.id,nn);return nn}
  function edgeClass(type){const t=String(type||'');if(financeRE.test(t))return'finance';if(moneyRE.test(t))return'money';if(controlRE.test(t))return'control';if(/REGISTERED_AGENT|AGENT_OF|SERVICE/i.test(t))return'agentlink';if(/ADDRESS|BUILDING|HQ|HEADQUARTER/i.test(t))return'address';return'source'}
  function addEdge(e){if(!e?.from||!e?.to||e.from===e.to)return;const type=esc(e.type||'RELATED_TO');const a=String(e.from)<String(e.to)?e.from:e.to,b=String(e.from)<String(e.to)?e.to:e.from,key=`${a}|${b}|${type}|${e.source||''}`;if(!S.edges.has(key))S.edges.set(key,{...e,type,key,className:edgeClass(type)})}
  function addAddressNodes(data,parentId,newIds){const grouped=new Map();for(const r of safeArray(data.addresses)){const a=r.address_variant||r.address;if(!a)continue;const pk=premiseKey(r,a),aid='addr:'+(pk||r.canonical_address_id||r.address_id||a.address_key||a.id);if(!grouped.has(aid))grouped.set(aid,{row:r,a,raw:{...r,address_premise_key:pk,variants:[],equivalent_address_ids:[]}});const g=grouped.get(aid);g.raw=mergeAddressRaw(g.raw,{...r,address_premise_key:pk,variants:[r.address_variant||r.address].filter(Boolean),equivalent_address_ids:r.equivalent_address_ids||[]});if(premiseLabel(a).length<premiseLabel(g.a).length)g.a=a}
    for(const[aid,g]of grouped){const r=g.row,a=g.a,pk=g.raw.address_premise_key||premiseKey(r,a),label=premiseLabel(a);const existed=S.nodes.has(aid),n=addNode({id:aid,label,kind:'address',historical:false,statuses:[],lifecycle:[],jurisdictions:uniq([a.region,a.country].map(esc)),sources:[],raw:g.raw},parentId);if(n&&!existed&&newIds&&!newIds.includes(aid))newIds.push(aid);addEdge({from:parentId,to:aid,type:esc(r.role||'HAS ADDRESS'),source:r.source_id||'address_index',evidence:{premise_key:pk,exact_key:r.address_exact_key,co_location_only:true}})}
  }
