  function svgEl(name,attrs={}){const e=document.createElementNS(NS,name);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,String(v));return e}
  function nodePremise(n){if(!n||n.kind!=='address')return'';const r=n.raw||{},a=r.address_variant||r.address||{};return esc(r.address_premise_key||r.address_merge_key||a.premise_key)||fallbackPremiseKey(a)}
  function addressFocus(){const sel=S.nodes.get(S.selected);if(!sel||sel.kind!=='address')return null;const pk=nodePremise(sel),addrIds=new Set();for(const n of S.nodes.values())if(n.kind==='address'&&nodePremise(n)===pk)addrIds.add(n.id);const nodes=new Set(addrIds),edgeKeys=new Set(),directEntities=new Set();for(const e of S.edges.values()){if(addrIds.has(e.from)||addrIds.has(e.to)){edgeKeys.add(e.key);nodes.add(e.from);nodes.add(e.to);const other=addrIds.has(e.from)?e.to:e.from;if(S.nodes.get(other)?.kind!=='address')directEntities.add(other)}}for(const e of S.edges.values()){if(directEntities.has(e.from)||directEntities.has(e.to)){const other=directEntities.has(e.from)?e.to:e.from;if(S.nodes.get(other)?.kind==='address'){edgeKeys.add(e.key);nodes.add(e.from);nodes.add(e.to)}}}return{premise_key:pk,addressIds:addrIds,nodes,edgeKeys,directEntities}}
  function wrapLines(text,max=27,limit=3){const words=esc(text).split(' '),lines=[];let cur='';for(const w of words){const next=(cur+' '+w).trim();if(next.length>max&&cur){lines.push(cur);cur=w;if(lines.length===limit-1)break}else cur=next}if(cur&&lines.length<limit)lines.push(cur);const used=lines.join(' ');if(used.length<esc(text).length&&lines.length)lines[lines.length-1]=lines[lines.length-1].replace(/…?$/,'')+'…';return lines}
  function render(){if(S.drag||S.pan){S.renderPending=true;return}S.renderPending=false;svg.textContent='';const af=addressFocus(),g=svgEl('g',{id:'viewport',transform:`translate(${S.tx} ${S.ty}) scale(${S.scale})`});
    const edgesLayer=svgEl('g');for(const e of S.edges.values()){const a=S.nodes.get(e.from),b=S.nodes.get(e.to);if(!a||!b)continue;const x1=a.x+a.w/2,y1=a.y+a.h/2,x2=b.x+b.w/2,y2=b.y+b.h/2;const cls=e.className||'source',color=COLORS[cls]||COLORS.source,focused=!af||af.edgeKeys.has(e.key);const baseWidth=cls==='money'?2.4:cls==='control'?2.2:cls==='finance'?2.1:cls==='agentlink'?2.0:cls==='address'?1.8:1.5;const line=svgEl('line',{x1,y1,x2,y2,stroke:color,'stroke-width':af&&focused?Math.max(3,baseWidth+.7):baseWidth,'stroke-opacity':af?(focused?0.98:0.08):(e.inferred?0.6:0.88),'data-from':e.from,'data-to':e.to});if(cls==='control')line.setAttribute('stroke-dasharray','10 5');else if(cls==='finance')line.setAttribute('stroke-dasharray','2 5');else if(cls==='agentlink')line.setAttribute('stroke-dasharray','8 4 2 4');else if(cls==='address')line.setAttribute('stroke-dasharray','3 4');if(e.inferred)line.setAttribute('stroke-dasharray',(line.getAttribute('stroke-dasharray')||'7 5')+' 3 5');edgesLayer.append(line)}g.append(edgesLayer);
    const nodesLayer=svgEl('g');for(const n of S.nodes.values()){const ng=svgEl('g',{'data-id':n.id,transform:`translate(${n.x} ${n.y})`,tabindex:'0'});ng.style.cursor=n.kind==='address'?'default':'pointer';if(af&&!af.nodes.has(n.id))ng.setAttribute('opacity','0.22');const stroke=COLORS[n.kind]||COLORS.company;const rect=svgEl('rect',{x:0,y:0,width:n.w,height:n.h,rx:6,fill:n.id===S.selected?'#0b1b24':'#051016',stroke,'stroke-width':n.id===S.selected?3:2});if(n.historical)rect.setAttribute('stroke-dasharray','7 4');ng.append(rect);const lines=wrapLines(n.label,n.kind==='address'?31:25,3),start=lines.length===1?28:lines.length===2?23:18;lines.forEach((t,i)=>{const tx=svgEl('text',{x:n.w/2,y:start+i*14,'text-anchor':'middle',fill:'#eef7fa','font-size':'11','font-weight':'700'});tx.textContent=t;ng.append(tx)});const sub=svgEl('text',{x:n.w/2,y:n.h-8,'text-anchor':'middle',fill:n.loading?'#19d7e7':'#58798a','font-size':'7'});sub.textContent=n.loading?'LOADING…':n.historical?`${n.kind.toUpperCase()} • HISTORICAL`:n.kind.toUpperCase();ng.append(sub);bindNodePointer(ng,n);nodesLayer.append(ng)}g.append(nodesLayer);svg.append(g);$('nc').textContent=String(S.nodes.size);$('ec').textContent=String(S.edges.size);$('remove').disabled=!S.selected}

  function rootPoint(ev){const p=svg.createSVGPoint();p.x=ev.clientX;p.y=ev.clientY;const m=svg.getScreenCTM();return m?p.matrixTransform(m.inverse()):{x:ev.clientX,y:ev.clientY}}
  function worldPoint(ev){const vp=svg.querySelector('#viewport'),p=svg.createSVGPoint();p.x=ev.clientX;p.y=ev.clientY;const m=vp?.getScreenCTM?.();if(m)return p.matrixTransform(m.inverse());const r=rootPoint(ev);return{x:(r.x-S.tx)/S.scale,y:(r.y-S.ty)/S.scale}}
  function applyViewport(){const vp=svg.querySelector('#viewport');if(vp)vp.setAttribute('transform',`translate(${S.tx} ${S.ty}) scale(${S.scale})`)}
  function findNodeEl(id){for(const el of svg.querySelectorAll('[data-id]'))if(el.getAttribute('data-id')===id)return el;return null}
  function updateNodeGeometry(id){const n=S.nodes.get(id),el=findNodeEl(id);if(!n||!el)return;el.setAttribute('transform',`translate(${n.x} ${n.y})`);for(const line of svg.querySelectorAll('line[data-from][data-to]')){const a=S.nodes.get(line.getAttribute('data-from')),b=S.nodes.get(line.getAttribute('data-to'));if(!a||!b)continue;line.setAttribute('x1',a.x+a.w/2);line.setAttribute('y1',a.y+a.h/2);line.setAttribute('x2',b.x+b.w/2);line.setAttribute('y2',b.y+b.h/2)}}
  function flushRender(){if(S.renderPending&&!S.drag&&!S.pan){S.renderPending=false;render()}}
  function bindNodePointer(el,n){
    el.addEventListener('pointerdown',ev=>{if(ev.button!==0)return;ev.preventDefault();ev.stopPropagation();const p=worldPoint(ev);S.drag={id:n.id,grabX:p.x-n.x,grabY:p.y-n.y,startClientX:ev.clientX,startClientY:ev.clientY,moved:false,pid:ev.pointerId};el.style.cursor='grabbing';el.setPointerCapture?.(ev.pointerId)});
    el.addEventListener('pointermove',ev=>{if(!S.drag||S.drag.id!==n.id||S.drag.pid!==ev.pointerId)return;const screenMove=Math.hypot(ev.clientX-S.drag.startClientX,ev.clientY-S.drag.startClientY);if(screenMove>4)S.drag.moved=true;if(!S.drag.moved)return;const p=worldPoint(ev);n.x=p.x-S.drag.grabX;n.y=p.y-S.drag.grabY;S.manual=true;updateNodeGeometry(n.id)});
    el.addEventListener('pointerup',ev=>{if(!S.drag||S.drag.id!==n.id||S.drag.pid!==ev.pointerId)return;const moved=S.drag.moved;try{el.releasePointerCapture?.(ev.pointerId)}catch{}el.style.cursor=n.kind==='address'?'default':'pointer';S.drag=null;if(moved){updateNodeGeometry(n.id);flushRender();return}scheduleInspect(n.id);flushRender()});
    el.addEventListener('pointercancel',ev=>{try{el.releasePointerCapture?.(ev.pointerId)}catch{}el.style.cursor=n.kind==='address'?'default':'pointer';S.drag=null;flushRender()});
    el.addEventListener('dblclick',ev=>{ev.preventDefault();ev.stopPropagation();if(S.clickTimer){clearTimeout(S.clickTimer);S.clickTimer=null}if(n.kind==='address'){selectNode(n.id,true);return}expandNode(n.id)})
  }
  function scheduleInspect(id){if(S.clickTimer)clearTimeout(S.clickTimer);S.clickTimer=setTimeout(()=>{S.clickTimer=null;selectNode(id,true)},230)}

  // Robust whole-graph pan: screen-pixel delta -> SVG viewBox units. Window listeners keep the gesture alive outside the SVG.
  svg.addEventListener('pointerdown',ev=>{
    const nodeTarget=ev.target instanceof Element?ev.target.closest('[data-id]'):null;
    if(nodeTarget||ev.button!==0||S.drag)return;
    ev.preventDefault();
    const rect=svg.getBoundingClientRect(),vb=svg.viewBox.baseVal;
    S.pan={pid:ev.pointerId,startClientX:ev.clientX,startClientY:ev.clientY,tx:S.tx,ty:S.ty,sx:(vb?.width||1120)/Math.max(1,rect.width),sy:(vb?.height||650)/Math.max(1,rect.height)};
    svg.classList.add('panning');
  });
  window.addEventListener('pointermove',ev=>{if(!S.pan||S.pan.pid!==ev.pointerId)return;ev.preventDefault();S.tx=S.pan.tx+(ev.clientX-S.pan.startClientX)*S.pan.sx;S.ty=S.pan.ty+(ev.clientY-S.pan.startClientY)*S.pan.sy;S.manual=true;applyViewport()},{passive:false});
  const endPan=ev=>{if(!S.pan||ev?.pointerId!==S.pan.pid)return;S.pan=null;svg.classList.remove('panning');flushRender()};
  window.addEventListener('pointerup',endPan);window.addEventListener('pointercancel',endPan);

  svg.addEventListener('wheel',ev=>{ev.preventDefault();const p=rootPoint(ev),old=S.scale,next=Math.max(.18,Math.min(3.5,old*(ev.deltaY<0?1.12:.89))),wx=(p.x-S.tx)/old,wy=(p.y-S.ty)/old;S.scale=next;S.tx=p.x-wx*next;S.ty=p.y-wy*next;S.manual=true;applyViewport()},{passive:false});

  function placeNew(parentId,ids){const p=S.nodes.get(parentId);if(!p)return;const fresh=ids.map(id=>S.nodes.get(id)).filter(Boolean);if(!fresh.length)return;const gapY=95,total=(fresh.length-1)*gapY;fresh.forEach((n,i)=>{if(n._placed)return;n.x=p.x+320;n.y=p.y-total/2+i*gapY;n._placed=true;resolveCollision(n)})}
  function resolveCollision(n){for(let guard=0;guard<80;guard++){let hit=false;for(const o of S.nodes.values()){if(o===n)continue;if(Math.abs((n.x+n.w/2)-(o.x+o.w/2))<(n.w+o.w)/2+28&&Math.abs((n.y+n.h/2)-(o.y+o.h/2))<(n.h+o.h)/2+22){n.y=o.y+o.h+28;hit=true;break}}if(!hit)break}}
  function arrange(){if(!S.nodes.size)return;const root=S.root&&S.nodes.has(S.root)?S.root:[...S.nodes.keys()][0],adj=new Map();for(const id of S.nodes.keys())adj.set(id,new Set());for(const e of S.edges.values()){adj.get(e.from)?.add(e.to);adj.get(e.to)?.add(e.from)}const level=new Map([[root,0]]),q=[root];while(q.length){const a=q.shift(),l=level.get(a);for(const b of adj.get(a)||[]){if(!level.has(b)){level.set(b,l+1);q.push(b)}}}let max=Math.max(0,...level.values());for(const id of S.nodes.keys())if(!level.has(id))level.set(id,++max);const groups=new Map();for(const[id,l]of level){if(!groups.has(l))groups.set(l,[]);groups.get(l).push(S.nodes.get(id))}for(const[l,arr]of [...groups.entries()].sort((a,b)=>a[0]-b[0])){arr.sort((a,b)=>a.kind===b.kind?a.label.localeCompare(b.label):(a.kind==='address'?1:-1));const gap=105,total=(arr.length-1)*gap;arr.forEach((n,i)=>{n.x=l*315;n.y=i*gap-total/2;n._placed=true})}S.manual=false;fitAll(40);event('Arranged graph into collision-free depth columns.')}
  function bounds(){if(!S.nodes.size)return{x:0,y:0,w:100,h:100};const xs=[],ys=[],xe=[],ye=[];for(const n of S.nodes.values()){xs.push(n.x);ys.push(n.y);xe.push(n.x+n.w);ye.push(n.y+n.h)}const x=Math.min(...xs),y=Math.min(...ys),r=Math.max(...xe),b=Math.max(...ye);return{x,y,w:Math.max(1,r-x),h:Math.max(1,b-y)}}
  function fitAll(pad=55){if(!S.nodes.size)return;const b=bounds(),vb=svg.viewBox.baseVal,w=vb?.width||1120,h=vb?.height||650,sc=Math.max(.18,Math.min(2.4,Math.min((w-pad*2)/b.w,(h-pad*2)/b.h)));S.scale=sc;S.tx=(w-b.w*sc)/2-b.x*sc;S.ty=(h-b.h*sc)/2-b.y*sc;S.manual=false;render()}
  function zoom(f){const vb=svg.viewBox.baseVal,px=(vb?.x||0)+(vb?.width||1120)/2,py=(vb?.y||0)+(vb?.height||650)/2,old=S.scale,next=Math.max(.18,Math.min(3.5,old*f)),wx=(px-S.tx)/old,wy=(py-S.ty)/old;S.scale=next;S.tx=px-wx*next;S.ty=py-wy*next;S.manual=true;applyViewport()}
