  function normalizeSearchRows(rows){const m=new Map();for(const r of safeArray(rows)){const id=r.identity_id||r.parent_identity_id;if(!id)continue;const n=normIdentity(r),k=id;if(!m.has(k))m.set(k,{...r,identity_id:id,canonical_name:n.label,jurisdictions:n.jurisdictions,statuses:n.statuses});else{const a=m.get(k);a.jurisdictions=uniq([...(safeArray(a.jurisdictions)),...n.jurisdictions]);a.statuses=uniq([...(safeArray(a.statuses)),...n.statuses]);a.sources=[...(safeArray(a.sources)),...(safeArray(r.sources))]}}return [...m.values()]}
  function showResults(rows){const box=$('results');box.textContent='';const list=normalizeSearchRows(rows).slice(0,80);S.activeResult=-1;box._rows=list;if(!list.length){const x=document.createElement('div');x.className='result';x.textContent='No matching canonical identities yet.';box.append(x);box.classList.add('open');return}list.forEach((r,i)=>{const n=normIdentity(r),row=document.createElement('div');row.className='result';row.dataset.i=String(i);const left=document.createElement('div'),name=document.createElement('div');name.className='name';name.textContent=n.label;const sub=document.createElement('div');sub.className='sub';sub.textContent=[n.jurisdictions.join(' · '),safeArray(r.member_types).join('/'),n.statuses.join(' · ')].filter(Boolean).join(' • ');left.append(name,sub);const score=document.createElement('div');score.className='score';score.textContent=r.score!=null?Number(r.score).toFixed(2):`${r.member_count||1} rec`;row.append(left,score);row.addEventListener('pointerdown',ev=>ev.preventDefault());row.addEventListener('click',()=>seed(r));box.append(row)});box.classList.add('open')}
  function closeResults(){$('results').classList.remove('open');S.activeResult=-1}
  async function typeahead(){const q=$('q').value.trim(),seq=++S.searchSeq;if(!S.typed||q.length<2){closeResults();return}try{const b=await get(`/corporate-registry?q=${encodeURIComponent(q)}&limit=24`,10000);if(seq!==S.searchSeq)return;showResults(b.results||[])}catch(e){if(seq===S.searchSeq)status(`Typeahead error: ${e.message}`,'err')}}
  let typeTimer=null;
  $('q').addEventListener('input',()=>{S.typed=true;clearTimeout(typeTimer);typeTimer=setTimeout(typeahead,300)});
  $('q').addEventListener('keydown',ev=>{const box=$('results'),rows=box._rows||[];if(ev.key==='Escape'){closeResults();$('q').blur();return}if((ev.key==='ArrowDown'||ev.key==='ArrowUp')&&box.classList.contains('open')&&rows.length){ev.preventDefault();S.activeResult=ev.key==='ArrowDown'?Math.min(rows.length-1,S.activeResult+1):Math.max(0,S.activeResult-1);[...box.querySelectorAll('.result')].forEach((el,i)=>el.classList.toggle('active',i===S.activeResult));return}if(ev.key==='Enter'){ev.preventDefault();if(box.classList.contains('open')&&S.activeResult>=0&&rows[S.activeResult])seed(rows[S.activeResult]);else deepSearch()}});
  $('q').addEventListener('blur',()=>setTimeout(closeResults,150));$('results').addEventListener('pointerdown',ev=>ev.stopPropagation());

  async function pool(items,worker,limit=3){let i=0;const out=[];async function run(){while(i<items.length){const idx=i++;try{out[idx]=await worker(items[idx])}catch(e){out[idx]={error:e.message}}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},run));return out}
  function updateStateRows(rows){for(const r of safeArray(rows)){const code=r.state||r.code;if(!code)continue;const old=S.stateRows.get(code)||{};S.stateRows.set(code,{...old,...r})}renderStates()}
  async function deepSearch(){const q=$('q').value.trim();if(q.length<2)return;const seq=++S.deepSeq;status(`Searching indexed graph + current live registries for “${q}”…`,'wait');event(`Search all states: ${q}`);closeResults();let fast=[];try{const b=await get(`/corporate-registry?q=${encodeURIComponent(q)}&limit=80`,12000);fast=b.results||[];if(seq!==S.deepSeq)return;if(fast.length)showResults(fast)}catch{}
    try{const [sweep,dir]=await Promise.all([get(`/corporate-all-states-search?q=${encodeURIComponent(q)}`,60000),loadDirectory(false)]);if(seq!==S.deepSeq)return;updateStateRows(sweep.states||[]);let rows=[...fast,...safeArray(sweep.results)];const extras=[...S.liveStates].filter(st=>!BASE_SWEEP_NATIVE.has(st));if(extras.length){status(`Base sweep complete. Refreshing ${extras.length} additional live registries…`,'wait');const extra=await pool(extras,async st=>{const b=await get(`/corporate-state-adapter?q=${encodeURIComponent(q)}&state=${st}&refresh=1`,25000);return{st,b}},3);for(const x of extra){if(x?.b){rows.push(...safeArray(x.b.results));updateStateRows(x.b.sources||[])}}}if(seq!==S.deepSeq)return;showResults(rows);const hits=normalizeSearchRows(rows).length;status(`Search complete • ${hits} canonical identities • ${S.liveStates.size} validated live registries + indexed/official routes for all 51.`);event(`Search complete: ${hits} canonical identities.`)}catch(e){status(`Search degraded: ${e.message}`,'err');event(`Search degraded: ${e.message}`)}}

  async function loadDirectory(renderIt=true){try{const b=await get('/corporate-state-directory',15000);S.liveStates=new Set(safeArray(b.live_states));for(const r of safeArray(b.states))S.stateRows.set(r.code,{...r,state:r.code});if(renderIt)renderStates();$('coverageSummary').textContent=`${S.liveStates.size} live / 51 routed`;return b}catch(e){$('coverageSummary').textContent='directory unavailable';if(renderIt)renderStates();return{states:[],live_states:[]}}}
  function renderStates(){const box=$('stategrid');box.textContent='';const codes=['AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY','DC'];for(const c of codes){const r=S.stateRows.get(c)||{},d=document.createElement('div'),live=S.liveStates.has(c),err=r.ok===false||/error/i.test(String(r.status||''));d.className='state '+(err?'err':live?'live':'portal')+(Number(r.count||0)>0?' hit':'');d.title=[r.name||c,live?'validated live machine source':'indexed + official portal route',r.status,r.count?`${r.count} hits`:null].filter(Boolean).join(' • ');d.textContent=c+(Number(r.count||0)>0?` ${r.count}`:live?' ●':'');box.append(d)}}

  function removeSelected(){const id=S.selected;if(!id)return;S.nodes.delete(id);for(const[k,e]of [...S.edges])if(e.from===id||e.to===id)S.edges.delete(k);S.selected=null;if(S.root===id)S.root=S.nodes.size?[...S.nodes.keys()][0]:null;$('details').textContent='Select a node.';$('details').classList.add('muted');render();event('Removed selected node from view (source data unchanged).')}
  function clearGraph(){S.nodes.clear();S.edges.clear();S.selected=null;S.root=null;S.scale=1;S.tx=0;S.ty=0;S.manual=false;S.pan=null;S.drag=null;S.renderPending=false;$('details').textContent='Select a node.';$('details').classList.add('muted');$('crumb').textContent='No active path';$('hist').textContent='Nothing yet.';$('hist').classList.add('muted');status('Ready.');render()}
  function exportPNG(){if(!S.nodes.size){toast('Nothing to export');return}const b=bounds(),pad=70,w=Math.ceil(b.w+pad*2),h=Math.ceil(b.h+pad*2),clone=svgEl('svg',{xmlns:NS,width:w,height:h,viewBox:`${b.x-pad} ${b.y-pad} ${w} ${h}`});const bg=svgEl('rect',{x:b.x-pad,y:b.y-pad,width:w,height:h,fill:'#03080c'});clone.append(bg);const original=svg.querySelector('#viewport');if(!original)return;const content=original.cloneNode(true);content.setAttribute('transform','');clone.append(content);const xml=new XMLSerializer().serializeToString(clone),blob=new Blob([xml],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const scale=Math.min(2,Math.max(1,2400/Math.max(w,h))),c=document.createElement('canvas');c.width=Math.ceil(w*scale);c.height=Math.ceil(h*scale);const ctx=c.getContext('2d');ctx.fillStyle='#03080c';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);c.toBlob(p=>{const a=document.createElement('a');a.href=URL.createObjectURL(p);a.download=`open-corporate-graph-${Date.now()}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)},'image/png')};img.onerror=()=>{URL.revokeObjectURL(url);toast('PNG export failed')};img.src=url;event('Exported full graph PNG.')}

  $('go').onclick=deepSearch;$('clear').onclick=clearGraph;$('arrange').onclick=arrange;$('fit').onclick=()=>fitAll();$('zin').onclick=()=>zoom(1.2);$('zout').onclick=()=>zoom(.83);$('png').onclick=exportPNG;$('remove').onclick=removeSelected;$('auto').onclick=()=>{S.auto=!S.auto;$('auto').textContent=`AUTO ENRICH ${S.auto?'ON':'OFF'}`;event(`Auto enrich ${S.auto?'enabled':'disabled'}.`)};
  window.addEventListener('resize',()=>{if(S.nodes.size&&!S.manual)fitAll(45)});
  window.addEventListener('error',ev=>{status(`UI error: ${ev.message}`,'err');event(`UI error: ${ev.message}`)});
  render();renderStates();loadDirectory();
