const D=window.FUEL_DATA,NS='http://www.w3.org/2000/svg',$=s=>document.querySelector(s),byId=new Map(D.nodes.map(n=>[n.id,n]));
const family={CONTROLS:'control',OWNS_ASSET:'control',JV_INTEREST:'control',MANAGING_MEMBER:'control',OPERATES:'infrastructure',CONNECTED:'infrastructure',BRANDS:'brand',ACQUIRED:'transaction',SOLD:'transaction',ACQUISITION_CASE:'transaction',REGULATORY:'regulatory',REGISTERED_AGENT:'agent',SERVICE_GROUP:'agent',ADDRESS:'address',OFFICER:'officer'};
const layers={accounting:['Accounting consolidation','#67c4dd'],registry:['Registry / record custody','#8aa9d8'],context:['Master-network context','#a0a9bd'],unresolved:['Unresolved / missing links','#d58e8e'],control:['Ownership / management','#5de2c0'],infrastructure:['Infrastructure','#64b8ff'],brand:['Retail / branding','#ed9d6f'],transaction:['Historical transactions','#e6c777'],regulatory:['Regulatory records','#f48395'],agent:['Agent / service','#b998f5'],address:['Shared addresses','#718fae'],officer:['People / officers','#e9a9d9']};
const state={view:'all',evidence:'all',query:'',enabled:new Set(Object.keys(layers)),selected:null,focus:null,x:0,y:0,k:.65,history:[]};let visibleNodes=[],visibleEdges=[],drag=null,moved=false;
function el(tag,attrs={},txt){const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(txt!==undefined)e.textContent=txt;return e}
function safe(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function sourceHTML(id){const s=D.sources[id];return `<div class="source">${s.url?`<a target="_blank" rel="noopener" href="${safe(s.url)}">${safe(s.title)} ↗</a>`:safe(s.title)}<small>${safe(s.date)} · ${safe(s.kind)}</small></div>`}
function statusOf(n){const es=D.edges.filter(e=>e.a===n.id||e.b===n.id);return es.some(e=>e.status==='primary')?'primary':es.length?'mapped':'lead'}
function saveHistory(){state.history.push({x:state.x,y:state.y,k:state.k,focus:state.focus,selected:state.selected});if(state.history.length>30)state.history.shift()}
function filter(){let ns=D.nodes.filter(n=>state.view==='all'||(state.view==='fuel'?n.group==='fuel':n.group==='service'));
 if(state.view!=='all'){const ids=new Set(ns.map(n=>n.id));D.edges.forEach(e=>{if(ids.has(e.a)||ids.has(e.b)){[e.a,e.b].forEach(id=>{if(!ns.some(n=>n.id===id))ns.push(byId.get(id))})}})}
 if(state.focus){const ids=new Set([state.focus]);D.edges.filter(e=>e.a===state.focus||e.b===state.focus).forEach(e=>{ids.add(e.a);ids.add(e.b)});ns=ns.filter(n=>ids.has(n.id))}
 if(state.evidence!=='all')ns=ns.filter(n=>state.evidence==='lead'?statusOf(n)==='lead':D.edges.some(e=>(e.a===n.id||e.b===n.id)&&e.status===state.evidence));
 const ids=new Set(ns.map(n=>n.id));visibleEdges=D.edges.filter(e=>ids.has(e.a)&&ids.has(e.b)&&state.enabled.has((e.layer||family[e.type]))&&(state.evidence==='all'||state.evidence===e.status));visibleNodes=ns;
}
function transform(){ $('#world').setAttribute('transform',`translate(${state.x},${state.y}) scale(${state.k})`);$('#zoom').textContent=Math.round(state.k*100)+'%'}
function wrap(label){const words=label.split(' '),lines=[''];for(const w of words){let i=lines.length-1;if((lines[i]+' '+w).length>24&&lines[i])lines.push(w);else lines[i]+=(lines[i]?' ':'')+w}return lines.slice(0,3)}
function render(){filter();const world=$('#world');world.replaceChildren();const q=state.query.toLowerCase();const neighbors=new Set([state.selected]);visibleEdges.filter(e=>e.a===state.selected||e.b===state.selected).forEach(e=>{neighbors.add(e.a);neighbors.add(e.b)});
 for(const e of visibleEdges){const a=byId.get(e.a),b=byId.get(e.b),color=layers[(e.layer||family[e.type])][1];const path=el('path',{d:`M ${a.x+95} ${a.y+38} L ${b.x+95} ${b.y+38}`,fill:'none',stroke:color,'stroke-width':state.selected&&(e.a===state.selected||e.b===state.selected)?3:1.6,'stroke-dasharray':e.status==='primary'?'none':'6 5',opacity:state.selected&&!neighbors.has(e.a)?.2:.65,class:'edge'});path.append(el('title',{},`${a.label} → ${b.label}: ${e.type}`));path.addEventListener('click',ev=>{ev.stopPropagation();inspectEdge(e)});world.append(path);
 const dx=b.x-a.x,dy=b.y-a.y,angle=Math.atan2(dy,dx),mx=(a.x+b.x)/2+95,my=(a.y+b.y)/2+38;world.append(el('path',{d:`M ${mx-7*Math.cos(angle-.45)} ${my-7*Math.sin(angle-.45)} L ${mx} ${my} L ${mx-7*Math.cos(angle+.45)} ${my-7*Math.sin(angle+.45)}`,fill:'none',stroke:color,'stroke-width':1.6,'pointer-events':'none'}));}
 for(const n of visibleNodes){const st=statusOf(n),color=st==='primary'?'#5de2c0':st==='mapped'?'#eebc69':'#8497ab',match=!q||(n.label+' '+n.note).toLowerCase().includes(q),g=el('g',{class:'node',transform:`translate(${n.x},${n.y})`,tabindex:0,role:'button','aria-label':n.label,opacity:!match?.15:state.selected&&!neighbors.has(n.id)?.35:1,'data-id':n.id});g.append(el('rect',{width:190,height:76,rx:8,fill:state.selected===n.id?'#1c3837':'#121f2c',stroke:state.selected===n.id?'#ffffff':color,'stroke-width':state.selected===n.id?2.5:1.2,'stroke-dasharray':st==='lead'?'3 3':'none'}));g.append(el('rect',{x:0,y:14,width:3,height:48,fill:color}));wrap(n.label).forEach((line,i)=>g.append(el('text',{x:12,y:25+i*17,fill:'#e7eef5','font-size':14,'font-weight':600},line)));g.append(el('text',{x:12,y:65,fill:'#9caebf','font-size':11},n.type));g.append(el('title',{},n.note));g.addEventListener('click',ev=>{ev.stopPropagation();if(!moved)select(n.id,false)});g.addEventListener('dblclick',ev=>{ev.preventDefault();isolate(n.id)});g.addEventListener('keydown',ev=>{if(ev.key==='Enter'){ev.preventDefault();select(n.id,true)}});g.addEventListener('pointerdown',ev=>startDrag(ev,n));world.append(g)}
 transform();$('#stats').textContent=`${visibleNodes.length} nodes · ${visibleEdges.length} relationships`;$('#empty').hidden=visibleNodes.length>0;renderResults();}
function renderResults(){const q=state.query.toLowerCase(),list=visibleNodes.filter(n=>(n.label+' '+n.note).toLowerCase().includes(q));$('#count').textContent=list.length;$('#results').innerHTML=list.map(n=>`<button class="result" data-node="${n.id}">${safe(n.label)}<small>${safe(n.type)}</small></button>`).join('');$('#results').querySelectorAll('button').forEach(b=>b.onclick=()=>select(b.dataset.node,true))}
function tab(which){$('#inspector').hidden=which!=='inspect';$('#coverage').hidden=which!=='coverage';$('#inspect-tab').classList.toggle('active',which==='inspect');$('#coverage-tab').classList.toggle('active',which==='coverage')}
function inspect(n){tab('inspect');const es=D.edges.filter(e=>e.a===n.id||e.b===n.id);$('#inspector').innerHTML=`<div class="eyebrow">${safe(n.type.toUpperCase())}</div><h2>${safe(n.label)}</h2><span class="badge ${statusOf(n)}">${statusOf(n)==='primary'?'Primary-source connection':statusOf(n)==='mapped'?'Prior-map claim':'Unresolved lead'}</span><p>${safe(n.note)}</p><div class="metric">${es.length}</div><p>Mapped relationships · not market share</p><button id="isolate">Isolate connected nodes</button><h3>Connections</h3>${es.length?es.map(e=>`<div class="card"><button data-edge="${e.id}">${safe(byId.get(e.a).label)} → ${safe(byId.get(e.b).label)}</button><small>${safe(e.type.replaceAll('_',' '))} · ${safe(e.status)}${e.date?' · '+e.date:''}</small></div>`).join(''):'<p>No validated relationship imported yet.</p>'}<h3>Node source</h3>${sourceHTML(n.source)}`;$('#isolate').onclick=()=>isolate(n.id);$('#inspector').querySelectorAll('[data-edge]').forEach(b=>b.onclick=()=>inspectEdge(D.edges.find(e=>e.id===b.dataset.edge)))}
function inspectEdge(e){tab('inspect');$('#inspector').innerHTML=`<div class="eyebrow">RELATIONSHIP EVIDENCE</div><h2>${safe(e.type.replaceAll('_',' '))}</h2><span class="badge ${e.status}">${e.status==='primary'?'Primary source':'Prior-map claim'}</span><p>${safe(byId.get(e.a).label)}<br>↓<br>${safe(byId.get(e.b).label)}</p><h3>Claim</h3><p>${safe(e.note)}</p>${e.date?'<p>Record date: '+e.date+'</p>':''}<h3>Reference</h3>${sourceHTML(e.source)}<h3>Resolution / validation</h3><p>${e.status==='primary'?'The linked primary source supports this stated relationship at the listed date. Scope is limited to that record; historical transactions are not current ownership assertions.':'Recovered from the saved generated map. The underlying registry instrument has not been revalidated in this edition; the claim is preserved without promoting it to proven control.'}</p><button id="from">Inspect source node</button>`;$('#from').onclick=()=>select(e.a,true)}
function select(id,center){if(!byId.has(id))throw new Error('Unknown node');state.selected=id;const n=byId.get(id);if(center){saveHistory();if(!visibleNodes.includes(n)){state.view='all';state.evidence='all';state.focus=null;syncControls()}const r=$('#graph').getBoundingClientRect();state.k=Math.max(.8,state.k);state.x=r.width/2-(n.x+95)*state.k;state.y=r.height/2-(n.y+38)*state.k}render();inspect(n)}
function isolate(id){saveHistory();state.focus=id;state.selected=id;render();fit(false);inspect(byId.get(id));$('#view-title').textContent='Connected to '+byId.get(id).label}
function fit(history=true){if(history)saveHistory();if(!visibleNodes.length)return;const r=$('#graph').getBoundingClientRect(),minX=Math.min(...visibleNodes.map(n=>n.x))-35,minY=Math.min(...visibleNodes.map(n=>n.y))-80,maxX=Math.max(...visibleNodes.map(n=>n.x))+225,maxY=Math.max(...visibleNodes.map(n=>n.y))+115;state.k=Math.max(.15,Math.min(1.2,r.width/(maxX-minX),r.height/(maxY-minY)));state.x=(r.width-(maxX-minX)*state.k)/2-minX*state.k;state.y=(r.height-(maxY-minY)*state.k)/2-minY*state.k;transform()}
function zoom(factor,cx,cy){const r=$('#graph').getBoundingClientRect();cx??=r.width/2;cy??=r.height/2;const old=state.k;state.k=Math.min(2.5,Math.max(.15,old*factor));state.x=cx-(cx-state.x)*state.k/old;state.y=cy-(cy-state.y)*state.k/old;transform()}
function startDrag(ev,node){if(ev.button!==0)return;ev.stopPropagation();moved=false;drag={id:ev.pointerId,startX:ev.clientX,startY:ev.clientY,lastX:ev.clientX,lastY:ev.clientY,node};$('#graph').setPointerCapture(ev.pointerId)}
$('#graph').addEventListener('pointerdown',ev=>startDrag(ev,null));$('#graph').addEventListener('pointermove',ev=>{if(!drag||ev.pointerId!==drag.id)return;const dx=ev.clientX-drag.lastX,dy=ev.clientY-drag.lastY;if(Math.hypot(ev.clientX-drag.startX,ev.clientY-drag.startY)>4)moved=true;drag.lastX=ev.clientX;drag.lastY=ev.clientY;if(drag.node){drag.node.x+=dx/state.k;drag.node.y+=dy/state.k;render()}else{state.x+=dx;state.y+=dy;transform()}});$('#graph').addEventListener('pointerup',ev=>{const d=drag;drag=null;if(d&&d.node&&!moved)select(d.node.id,false)});$('#graph').addEventListener('pointercancel',()=>drag=null);$('#graph').addEventListener('wheel',ev=>{ev.preventDefault();const r=$('#graph').getBoundingClientRect();zoom(Math.exp(-ev.deltaY*.0015),ev.clientX-r.left,ev.clientY-r.top)},{passive:false});
for(const[id,[label,color]]of Object.entries(layers)){const l=document.createElement('label');l.className='layer';l.innerHTML=`<input type="checkbox" checked data-layer="${id}"><span class="swatch" style="border-color:${color}"></span>${label}`;$('#layers').append(l);l.querySelector('input').onchange=ev=>{ev.target.checked?state.enabled.add(id):state.enabled.delete(id);render()}}
$('#search').oninput=ev=>{state.query=ev.target.value;render()};$('#evidence').onchange=ev=>{state.evidence=ev.target.value;state.selected=null;render();fit()};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{saveHistory();state.view=b.dataset.view;state.focus=null;state.selected=null;syncControls();render();fit(false)});
function syncControls(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));$('#evidence').value=state.evidence;$('#search').value=state.query;$('#view-title').textContent=state.view==='all'?'The connected picture':state.view==='fuel'?'Fuel & infrastructure':'Corporate-service bridges'}
$('#fit').onclick=()=>fit();$('#plus').onclick=()=>zoom(1.25);$('#minus').onclick=()=>zoom(.8);$('#back').onclick=()=>{const old=state.history.pop();if(old){Object.assign(state,old);render();if(state.selected)inspect(byId.get(state.selected))}};const initialPositions=new Map(D.nodes.map(n=>[n.id,[n.x,n.y]]));$('#arrange').onclick=()=>{D.nodes.forEach(n=>{[n.x,n.y]=initialPositions.get(n.id)});render();fit()};$('#reset').onclick=()=>{state.focus=null;state.selected=null;state.query='';state.view='all';state.evidence='all';state.enabled=new Set(Object.keys(layers));document.querySelectorAll('[data-layer]').forEach(c=>c.checked=true);syncControls();render();fit();overview()};$('#inspect-tab').onclick=()=>tab('inspect');$('#coverage-tab').onclick=()=>tab('coverage');$('#sources').innerHTML=Object.keys(D.sources).map(sourceHTML).join('');
function overview(){tab('inspect');$('#inspector').innerHTML='<div class="eyebrow">START WITH A CONNECTION</div><h2>Follow the fuel.<br>Keep the evidence.</h2><p>Select a company, address or connecting line to inspect its relationships and sources.</p><h3>Three useful entry points</h3><div class="card"><button data-entry="mpc">Marathon → MPLX → logistics ↗</button></div><div class="card"><button data-entry="elm">Dallas / 1601 Elm Street ↗</button></div><div class="card"><button data-entry="ct">Shell IT / CT service bridge ↗</button></div><h3>Local competition record</h3><p>FTC’s June 2021 Speedway settlement covered 293 local markets. The 2018 Sunoco review identified 18 potential local monopolies absent relief.</p><p>Those records are mapped separately from company control.</p><h3>Edition scope</h3><p>45 nodes · 35 relationships. Public X history is not fully imported. Prior-map claims remain distinct from primary-source links.</p>';document.querySelectorAll('[data-entry]').forEach(b=>b.onclick=()=>isolate(b.dataset.entry))}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3500)}
$('#json').onclick=()=>download(new Blob([JSON.stringify(D,null,2)],{type:'application/json'}),'fuel-network-edition-01.json');
// Render the filtered graph directly from vector geometry, independent of screen zoom.
function pngDimensions(width,height){
 const scale=Math.min(3,16384/width,16384/height,Math.sqrt(40000000/(width*height)));
 return {width:Math.max(1,Math.floor(width*scale)),height:Math.max(1,Math.floor(height*scale))};
}
$('#export').title='High-resolution PNG of the displayed graph, including nodes outside the viewport';
$('#export').textContent='Export HD PNG ↗';
$('#export').onclick=async()=>{
 const button=$('#export'),label=button.textContent;let url,canvas;
 if(!visibleNodes.length){toast('There are no nodes to export.');return;}
 button.disabled=true;button.textContent='Preparing PNG…';
 try{
  if(document.fonts)await document.fonts.ready;
  const bounds=$('#world').getBBox(),padding=40,width=bounds.width+padding*2,height=bounds.height+padding*2,size=pngDimensions(width,height);
  const svg=$('#graph').cloneNode(true);svg.setAttribute('xmlns',NS);svg.setAttribute('width',size.width);svg.setAttribute('height',size.height);
  svg.setAttribute('viewBox',`${bounds.x-padding} ${bounds.y-padding} ${width} ${height}`);
  svg.setAttribute('font-family',getComputedStyle($('#graph')).fontFamily);
  svg.setAttribute('text-rendering','geometricPrecision');svg.querySelector('#world').removeAttribute('transform');
  // The screen grid is viewport-sized; use a clean opaque background for export.
  [...svg.children].filter(n=>n.tagName.toLowerCase()==='rect').forEach(n=>n.remove());
  svg.querySelectorAll('.node').forEach(n=>n.setAttribute('opacity','1'));
  svg.querySelectorAll('.edge').forEach(n=>n.setAttribute('opacity','0.85'));
  url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml;charset=utf-8'}));
  const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('SVG rendering failed'));img.src=url;});
  canvas=document.createElement('canvas');canvas.width=size.width;canvas.height=size.height;
  const ctx=canvas.getContext('2d');if(!ctx)throw Error('Canvas unavailable');
  ctx.fillStyle='#091017';ctx.fillRect(0,0,size.width,size.height);ctx.drawImage(img,0,0,size.width,size.height);
  const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('PNG encoding failed');
  download(blob,`fuel-network-${size.width}x${size.height}.png`);toast(`PNG exported: ${size.width} × ${size.height} pixels`);
 }catch(error){toast('PNG export could not finish. Isolate a smaller section and try again.');}
 finally{if(url)URL.revokeObjectURL(url);if(canvas){canvas.width=0;canvas.height=0;}button.disabled=false;button.textContent=label;}
};
render();fit(false);overview();window.addEventListener('resize',()=>fit(false));
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'inspect_fuel_node',title:'Inspect fuel-network node',description:'Select an existing node and show its evidence in the visible inspector.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input.id!=='string'||!byId.has(input.id))throw new Error('Unknown node id');select(input.id,true);return{node:byId.get(input.id),relationships:D.edges.filter(e=>e.a===input.id||e.b===input.id)}}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
