/* Edition 02: actual master graph import and path exploration. */
const routePanel=document.createElement('section');routePanel.innerHTML='<div class="section-title">Trace the existing connections</div><label for="path-from">From</label><select id="path-from"></select><label for="path-to">To</label><select id="path-to"></select><label class="layer"><input type="checkbox" id="path-leads" checked> Include research leads</label><button id="trace" style="width:100%">Trace path</button><p id="path-status" role="status"></p>';
$('#evidence').after(routePanel);
const choices=[...D.nodes].sort((a,b)=>a.label.localeCompare(b.label)).map(n=>`<option value="${n.id}">${safe(n.label)}</option>`).join('');$('#path-from').innerHTML=choices;$('#path-to').innerHTML=choices;$('#path-from').value='exny';$('#path-to').value='master_googlenm';
let pathIds=null,pathEdgeIds=null;
function permitted(e,leads){if(e.type==='NAME_SEARCH_RESULT'||e.sourceStatus==='missing')return false;if(!leads&&(e.sourceStatus==='lead'||e.layer==='unresolved'||(e.status==='mapped'&&!e.sourceStatus)))return false;return true}
function traceRoute(from,to,leads=true){if(!byId.has(from)||!byId.has(to))throw Error('Unknown node');const parent=new Map([[from,null]]),queue=[from];for(let i=0;i<queue.length;i++){const current=queue[i];if(current===to)break;for(const e of D.edges){if(!permitted(e,leads))continue;const other=e.a===current?e.b:e.b===current?e.a:null;if(other&&!parent.has(other)){parent.set(other,{node:current,edge:e});queue.push(other)}}}if(!parent.has(to))return null;const nodes=[to],edges=[];for(let current=to;current!==from;){const p=parent.get(current);edges.unshift(p.edge);current=p.node;nodes.unshift(current)}return{nodes,edges}}
const baseFilter=filter;filter=function(){baseFilter();if(pathIds){visibleNodes=D.nodes.filter(n=>pathIds.has(n.id));visibleEdges=D.edges.filter(e=>pathEdgeIds?pathEdgeIds.has(e.id):pathIds.has(e.a)&&pathIds.has(e.b));}};
function showPath(from,to,leads=true){const route=traceRoute(from,to,leads);if(!route){$('#path-status').textContent='No traversable path in the imported data under these settings. Missing links are not crossed.';return null}saveHistory();state.focus=null;state.selected=null;state.view='all';state.evidence='all';state.query='';pathIds=new Set(route.nodes);pathEdgeIds=new Set(route.edges.map(e=>e.id));syncControls();render();fit(false);$('#view-title').textContent='Connection path';$('#path-status').textContent=route.edges.length+' relationships · mixed types, not a control chain';tab('inspect');$('#inspector').innerHTML=`<div class="eyebrow">EXISTING GRAPH PATH</div><h2>${safe(byId.get(from).label)} → ${safe(byId.get(to).label)}</h2><p>Connections can be traversed in either direction to explore the network. Each arrow in the inspector retains the source record’s direction. Registry, service and address links do not imply ownership.</p>${route.edges.map(e=>`<div class="card"><button data-path-edge="${e.id}">${safe(byId.get(e.a).label)} → ${safe(byId.get(e.b).label)}</button><small>${safe(e.type.replaceAll('_',' '))} · ${safe(e.sourceStatus||e.status)}</small></div>`).join('')}`;document.querySelectorAll('[data-path-edge]').forEach(b=>b.onclick=()=>inspectEdge(D.edges.find(e=>e.id===b.dataset.pathEdge)));return route}
$('#trace').onclick=()=>showPath($('#path-from').value,$('#path-to').value,$('#path-leads').checked);
function clearPath(){pathIds=null;pathEdgeIds=null;$('#path-status').textContent=''}
document.querySelectorAll('[data-view],#reset,#evidence').forEach(b=>b.addEventListener(b.id==='evidence'?'change':'click',clearPath,{capture:true}));
const baseIsolate=isolate;isolate=function(id){clearPath();baseIsolate(id)};
const baseSelect=select;select=function(id,center){if(center&&pathIds&&!pathIds.has(id))clearPath();baseSelect(id,center)};
const baseInspect=inspect;inspect=function(n){baseInspect(n);const btn=document.createElement('button');btn.textContent='Explore entire connected component';btn.style.marginTop='8px';btn.onclick=()=>showComponent(n.id);$('#isolate').after(btn);if(n.masterRecord){const box=document.createElement('div');box.innerHTML='<h3>Original master record</h3><p>'+safe(n.masterRecord.subtitle||'')+'</p><p>'+safe((n.masterRecord.evidence||[]).join(' · ')||'No instrument reference supplied in source node.')+'</p><small>Source node ID: '+safe(n.masterRecord.id)+'</small>';$('#inspector').append(box)}};
const oldEdgeInspect=inspectEdge;inspectEdge=function(e){if(e.source!=='master')return oldEdgeInspect(e);tab('inspect');const a=byId.get(e.a),b=byId.get(e.b);$('#inspector').innerHTML=`<div class="eyebrow">IMPORTED MASTER RELATIONSHIP</div><h2>${safe(e.type)}</h2><span class="badge mapped">Original status: ${safe(e.sourceStatus)}</span><p>${safe(a.label)}<br>↓<br>${safe(b.label)}</p>${e.date?'<p>Source year: '+safe(e.date)+'</p>':''}<h3>Claim</h3><p>${safe(e.note)}</p><h3>Reference / resolution</h3>${sourceHTML('master')}<p>Imported directly from version 6’s edge array. Original endpoints, label, year and status are retained. This confirms what the app recorded; it does not independently authenticate the underlying instrument.</p><h3>Endpoint evidence references</h3><p>${safe((a.masterRecord?.evidence||[]).concat(b.masterRecord?.evidence||[]).join(' · ')||'No instrument references supplied on these source nodes.')}</p><h3>Validation status</h3><p>${e.sourceStatus==='missing'?'The original graph marks this link missing. Path tracing will not cross it.':e.sourceStatus==='lead'?'The original graph marks this as a research lead. It can be excluded from path tracing.':'The original graph labels this '+safe(e.sourceStatus)+'. That label is inherited, not newly verified in this edition.'}</p><button id="edge-from">Inspect first node</button>`;$('#edge-from').onclick=()=>select(e.a,true)};
function showComponent(id){const seen=new Set([id]),queue=[id];for(let i=0;i<queue.length;i++){for(const e of D.edges){if(!permitted(e,$('#path-leads').checked))continue;const other=e.a===queue[i]?e.b:e.b===queue[i]?e.a:null;if(other&&!seen.has(other)){seen.add(other);queue.push(other)}}}state.focus=null;state.selected=null;pathIds=seen;pathEdgeIds=new Set(D.edges.filter(e=>seen.has(e.a)&&seen.has(e.b)&&permitted(e,$('#path-leads').checked)).map(e=>e.id));render();fit();$('#view-title').textContent='Connected component';$('#path-status').textContent=seen.size+' connected nodes; missing links excluded';inspect(byId.get(id))}
overview=function(){tab('inspect');$('#inspector').innerHTML=`<div class="eyebrow">EDITION 03 · SELF-EXPANDING NETWORK</div><h2>The network follows new records.</h2><p><b>${D.nodes.length} nodes · ${D.edges.length} relationships</b></p><p>All 140 nodes and 170 edges from Ultra Corporate Reference Web version 6 are imported. Eight matching entity/address nodes join that graph to the fuel edition.</p><p>Daily automatic discovery follows legal-entity identifiers into accounting relationships and exact addresses. Open the discovery panel to inspect the queue and raw evidence.</p><h3>Follow an existing path</h3><div class="card"><button id="sample-route">ExxonMobil NY → CSC → Google Compare ↗</button></div><div class="card"><button id="sample-ct">Shell IT → CT → Union Carbide ↗</button></div><div class="card"><button id="sample-zorro">ExxonMobil NY → Zorro Ranch ↗</button></div><p>Paths expose intermediary records and exact relationship types. They are not automatically ownership chains.</p><h3>Source completeness</h3><p>This import is complete for the recovered version 6 dataset. The original source still contains leads and document gaps. X posts and other unsaved versions are not claimed as fully imported.</p><a href="master-source.json" download>Download the original imported dataset</a>`;$('#sample-route').onclick=()=>showPath('exny','master_googlenm');$('#sample-ct').onclick=()=>showPath('shellit','master_unionak');$('#sample-zorro').onclick=()=>showPath('exny','master_zorro')};
$('#coverage').innerHTML=`<div class="eyebrow">ACTUAL APP DATA / VERSION 6</div><h2>Import audit</h2><p>Source: Ultra Corporate Reference Web. All 140 source nodes and 170 source edges retained. Eight existing fuel-map nodes were matched by entity/address identity; original master records remain attached.</p><p>Result: ${D.nodes.length} nodes and ${D.edges.length} relationships. Source node IDs, original edges, evidence notes and original statuses travel with the JSON export.</p><h3>Joined nodes</h3><p>Prentice-Hall; 80 State Street; Corporation Service Company; CT Corporation System; Prentice-Hall Kansas; Registered Agents Inc.; 30 N Gould Suite R; 5900 Balcones Suite 100.</p><h3>Provenance</h3><p>The older Full Corporate Web Map was inspected for comparison. Its overlapping historical assertions were not allowed to overwrite version 6. The imported app’s own sources include filing captures and older maps; importing its data does not upgrade their evidence status.</p><h3>Open coverage</h3><p>No full X account import is available. The Dallas petroleum branch remains as recorded in edition 01 because it is not present in the recovered version 6 dataset. Unconnected companies are not linked merely to make the picture continuous.</p><h3>Path rules</h3><p>Path tracing searches all imported relationships, in either direction. Missing edges are never crossed. Research leads can be included or excluded. Registry custody and same-address paths remain visibly distinct from control.</p><a href="master-source.json" download>Original graph + import audit ↗</a><h3>Sources</h3>${Object.keys(D.sources).map(sourceHTML).join('')}`;
$('#back').addEventListener('click',()=>{clearPath();render()},{capture:true});
window.FUEL_NETWORK_API={traceRoute,showPath,showComponent};
render();fit(false);overview();
