/* Government evidence remains an overlay; original graph claims are never promoted by name matching. */
(()=>{
 const G=window.FUEL_GOVERNMENT;if(!G)return;
 const labels={identifier_match:'CIK confirmed',identifier_conflict:'Identifier conflict — blocked',name_candidate:'Name candidate — unresolved',pending:'Filer record queued'};
 function recordHTML(r){return `<div class="card"><strong>${safe(r.name)}</strong><p>${safe(labels[r.status]||r.status)} · CIK ${safe(r.cik)}</p><p>${safe(r.reason)}</p>${r.nameMatches!==undefined?`<p>Current/former name comparison: ${r.nameMatches?"agrees":"differs — review"}</p>`:""}${r.jurisdictionComparison?`<p>Jurisdiction comparison: ${safe(r.jurisdictionComparison)}</p>`:''}${r.stateOfIncorporation?`<p>SEC-reported incorporation: ${safe(r.stateOfIncorporation)}</p>`:''}<p>Retrieved: ${safe(r.retrievedAt||'Not yet retrieved')}${r.stale?' · Prior successful evidence retained':''}</p>${r.fetchError?`<p>Latest fetch failed: ${safe(r.fetchError)}</p>`:''}<a href="${safe(r.url)}" target="_blank" rel="noopener">Government source JSON</a>${r.addresses?`<details><summary>Reported addresses and former names</summary><pre style="white-space:pre-wrap">${safe(JSON.stringify({addresses:r.addresses,formerNames:r.formerNames},null,2))}</pre></details>`:''}${r.filings.length?'<h4>Recent filings</h4>'+r.filings.map(f=>`<p><a href="${safe(f.url)}" target="_blank" rel="noopener">${safe(f.form)} · ${safe(f.filed)}</a><br><small>${safe(f.accession)}</small></p>`).join(''):''}</div>`;}
 function nyHTML(n){const c=G.stateRegistry?.checks[n.id];if(!c)return '<p>State registry: no automatic adapter for this node yet.</p>';return '<h3>New York corporate record</h3><p>'+safe(G.stateRegistry.scope)+'</p><p>Retrieved: '+safe(c.retrievedAt||'Pending')+(c.fetchError?' · Fetch failed: '+safe(c.fetchError)+'; prior evidence retained if available':'')+'</p><a target="_blank" rel="noopener" href="'+safe(c.url)+'">Official state dataset result</a>'+(!c.records.length?'<p>No matching record retrieved. This does not establish nonexistence.</p>':c.records.map(x=>'<div class="card"><strong>'+safe(x.record.current_entity_name)+'</strong><p>'+safe(x.status==='identifier_match'?'DOS identifier confirmed':x.status==='identifier_conflict'?'Identifier conflict — blocked':'Name candidate — unresolved')+'</p><p>'+safe(x.reason)+'</p><pre style="white-space:pre-wrap">'+safe(JSON.stringify(x.record,null,2))+'</pre></div>').join(''))+(c.truncated?'<p>Result limit reached; query is incomplete.</p>':'');}
 function nodeHTML(n){const c=G.checks[n.id];return `<h3>Government record check</h3>${c?`<p>Checked ${safe(c.checkedAt)}${c.directoryRetrievedAt?'<br>Directory retrieved '+safe(c.directoryRetrievedAt):''}</p>${c.records.length?c.records.map(recordHTML).join(''):`<p>${c.status==='source_unavailable'?'SEC directory unavailable; check incomplete.':'No exact normalized name match in the SEC ticker directory. This limited directory does not cover all companies or SEC filers.'}</p>`}`:'<p>This node is outside the automatic SEC entity check.</p>'}<p>SEC records alone do not validate state registration, registered agents or ownership instruments.</p>${n.registryId?`<p>Registry identifier to check: ${safe(n.registryId)} · ${safe(n.jurisdiction||'jurisdiction not supplied')} · ${safe(n.registry||'')}</p>`:''}`;}
 const oldInspect=inspect;inspect=function(n){oldInspect(n);const section=document.createElement('section');section.innerHTML=nodeHTML(n)+nyHTML(n);$('#inspector').append(section);};
 const oldEdge=inspectEdge;inspectEdge=function(e){oldEdge(e);const section=document.createElement('section');section.innerHTML='<h3>Government cross-check</h3><p>This relationship has not been validated by the SEC entity check. An endpoint’s filing record does not authenticate the connecting claim.</p>'+[e.a,e.b].map(id=>`<button data-gov-node="${safe(id)}">Check ${safe(byId.get(id).label)}</button>`).join('');section.querySelectorAll('[data-gov-node]').forEach(b=>b.onclick=()=>select(b.dataset.govNode,true));$('#inspector').append(section);};
 function showChecks(){tab('inspect');$('#inspector').innerHTML=`<div class="eyebrow">GOVERNMENT CROSS-CHECK</div><h2>Compare the map to filings</h2><p>${G.entitiesConsidered} entity nodes considered · ${G.candidateEntities} with directory candidates · ${G.recordsRetrieved} filer records retrieved · ${G.pending} queued</p><p>${G.run.succeeded}/${G.run.requests} requests succeeded this run · ${G.run.errors.length} failed</p><p>${safe(G.scope)}</p><p>New York: ${G.stateRegistry?.run.succeeded||0}/${G.stateRegistry?.run.requests||0} requests succeeded.</p><label for="gov-search">Find a checked map entity</label><input id="gov-search" placeholder="Company name"><div id="gov-results"></div><p><a href="government-checks.json" target="_blank">Download comparison results</a> · <a href="government-evidence.json" target="_blank">Raw government snapshots</a></p>`;
 const draw=()=>{const q=$('#gov-search').value.toLowerCase();const rows=Object.entries({...Object.fromEntries(Object.keys(G.stateRegistry?.checks||{}).map(id=>[id,{records:[],status:"not_in_sec_scope"}])),...G.checks}).filter(([id])=>byId.get(id).label.toLowerCase().includes(q)).sort((a,b)=>b[1].records.length-a[1].records.length);$('#gov-results').innerHTML=rows.map(([id,c])=>`<div class="card"><button data-gov-result="${safe(id)}">${safe(byId.get(id).label)}</button><small>${G.stateRegistry?.checks[id]?.records.some(r=>r.status==='identifier_match')?'NY DOS identifier confirmed':c.records.length?c.records.length+' SEC candidate(s)':c.status==='source_unavailable'?'Check unavailable':'No directory match'}</small></div>`).join('');$('#gov-results').querySelectorAll('[data-gov-result]').forEach(b=>b.onclick=()=>select(b.dataset.govResult,true));};$('#gov-search').oninput=draw;draw();
 }
 const panel=document.createElement('section');panel.innerHTML=`<div class="section-title">Government records</div><button id="government-checks">Check map against SEC records</button><p>${G.recordsRetrieved} filer records · ${G.pending} queued</p><p>Names, identifiers, incorporation, addresses and recent filings. New York DOS checks included; other state adapters pending.</p>`;$('#evidence').after(panel);$('#government-checks').onclick=showChecks;
 const coverage=document.createElement('section');coverage.innerHTML='<h3>Government cross-check coverage</h3><p>'+safe(G.scope)+'</p><p>Runs with the existing refresh. Failed fetches retain their last successful evidence. Candidates never create ownership edges or merge entities.</p>';$('#coverage').prepend(coverage);
})();
